### ISSUE TITLE
CLASS support

### ISSUE THREAD

**Issue by v0-e** [ika-rwth-aachen/etsi_its_messages#13]
Hey guys,
Let me start by thanking you for the great work on the whole ROS ecosystem and also this repo specifically, the community needs better ASN.1 <-> ROS tools like this one :)

On the issue, do you have any plans to support CLASS since it is included in recent ITS message versions like the last CPMs?
As you may know, `asn1tools` unfortunately does not support CLASS nor do I think there is a planned effort to do it.

There is also a seemingly inactive [work](https://github.com/virtual-vehicle/vehicle_captain_asn1_parser/tree/ros2_msg_parser_from_velichkov/librosmessageparser) by the @virtual-vehicle team which uses `asn1c` to parse the ASN.1 files and then create the ROS messages, missing only the headers-based conversion. Maybe something similar could be worth exploring.

Thanks!

**Comment by jpbusch** [comment]
Hi @v0-e,

Nice to read that you like our repo and that you are interested in improving it.
The issue you described is already known to us, but we don't have a concrete plan to solve it yet. If you are interested in helping us with this and also contributing to this repo, we would be happy to exchange ideas and work together to find the best solution.

We look forward to hearing from you!

**Comment by lreiher** [comment]
Current idea is to implement two backends (.msg, conversion headers) with https://github.com/librasn/rasn, a Rust library for parsing ASN.1.

**Comment by v0-e** [comment]
An update,
The roundtrip conversion for CAMs and DENMs seems to be working. Tested using the Converter/etsi_its_conversion app.
I'm currently working on the conversion for CPMv2 (with CLASS).

**Comment by v0-e** [comment]
CPMv2 conversion also seems to be working. Keep in mind though that the testing was not comprehensive, i.e., not all fields were tested as there are a lot, though the CLASS-related fields are ok.

On the integration of the new code generation tools with this repo, I have some comments/questions, 
1. Do you prefer running the code gen containerized like it is done with asn1c? Compiling the new code generators requires Rust to be installed;
2. Some complications may arise from the use of ETSI ITS CDD v1.3.1 and CDD v2.2.1 simultaneously, as some types with the same name are defined in both dictionaries. ROS also seems to have problems resolving stuff like `StationID` (v1.3.1) and `StationId` (v2.2.1). I fear that using different message versions in the same binary may result in some linking issues,  in both sides: on the asn1c generated code and ROS generated code. For example for the testing, I've modified the conversion package C++ code to only convert CPMv2, removing all the includes to CAM/DENM. A future solution for this maybe adding a prefix associated with the CDD version to all generated types;
3. I'll make a PR keeping the current Python-based code generation, adding the new tools as an option inside the `utils/` dir. I'll then continue the development of the new code gen from the standalone repo to this one;

**Comment by lreiher** [comment]
Closed with https://github.com/ika-rwth-aachen/etsi_its_messages/pull/17 and https://github.com/ika-rwth-aachen/etsi_its_messages/pull/20, CPM is here! 🚀
