### ISSUE TITLE
Support for CPM

### ISSUE THREAD

**Issue by lheg** [ika-rwth-aachen/etsi_its_messages#15]
Hey guys,

first of all, thanks a lot for this nice repository!

I wanted to ask if there is kind of a roadmap concerning support for the other message types, especially CPM, since I wanted to use this repository in my master thesis. Can you share any details about this?

Best regards
Lucas

**Comment by lreiher** [comment]
Hi Lucas,

thanks for your interest! We are currently in discussions on how to best tackle the CPM implementation, but unfortunately cannot guarantee any delivery date. For more details or to further discuss this, feel free to reach out to us via mail! :)

Lennart

**Comment by lreiher** [comment]
Closed with https://github.com/ika-rwth-aachen/etsi_its_messages/pull/17 and https://github.com/ika-rwth-aachen/etsi_its_messages/pull/20, CPM is here! 🚀
