### ISSUE TITLE
add package to ROS index for jazzy

### ISSUE THREAD

**Issue by riebl** [ika-rwth-aachen/etsi_its_messages#18]
I have built the current main branch without issues on ROS2 jazzy, so it should be rather easy to add the etsi_its_messages package. AFAIK, it is recommended to manually release a package the first time for each distribution.
Let me know if I can somehow assist your efforts. Thanks!

**Comment by gkueppers** [comment]
Closed with [Release v.2.1.0](https://github.com/ika-rwth-aachen/etsi_its_messages/releases/tag/v2.1.0)

**Comment by riebl** [comment]
I am sorry to come back on this issue: I see that etsi_its_messages are added to the ROS index for jazzy at https://index.ros.org/p/etsi_its_messages/github-ika-rwth-aachen-etsi_its_messages/#jazzy, but no pre-built packages seem to appear in the repository http://packages.ros.org/ros2/ubuntu/dists/noble/main.
The build job, however, seems to have run perfectly fine days ago: https://build.ros2.org/job/Jbin_uN64__etsi_its_messages__ubuntu_noble_amd64__binary/

Do you have any experience how long package publishing usually takes? Or am I completely on the wrong track here?

**Comment by lreiher** [comment]
They seem to be available now. :) To be honest, the exact release procedure is also a little intransparent to us.

```
root@eb3c8f8ebb9b:/# apt install ros-jazzy-etsi-its-messages
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libgeographiclib-dev libgeographiclib26 ros-jazzy-etsi-its-cam-coding ros-jazzy-etsi-its-cam-conversion ros-jazzy-etsi-its-cam-msgs ros-jazzy-etsi-its-coding ros-jazzy-etsi-its-conversion ros-jazzy-etsi-its-cpm-ts-coding
  ros-jazzy-etsi-its-cpm-ts-conversion ros-jazzy-etsi-its-cpm-ts-msgs ros-jazzy-etsi-its-denm-coding ros-jazzy-etsi-its-denm-conversion ros-jazzy-etsi-its-denm-msgs ros-jazzy-etsi-its-msgs ros-jazzy-etsi-its-msgs-utils
  ros-jazzy-etsi-its-primitives-conversion ros-jazzy-udp-msgs
Suggested packages:
  geographiclib-doc geographiclib-tools
The following NEW packages will be installed:
  libgeographiclib-dev libgeographiclib26 ros-jazzy-etsi-its-cam-coding ros-jazzy-etsi-its-cam-conversion ros-jazzy-etsi-its-cam-msgs ros-jazzy-etsi-its-coding ros-jazzy-etsi-its-conversion ros-jazzy-etsi-its-cpm-ts-coding
  ros-jazzy-etsi-its-cpm-ts-conversion ros-jazzy-etsi-its-cpm-ts-msgs ros-jazzy-etsi-its-denm-coding ros-jazzy-etsi-its-denm-conversion ros-jazzy-etsi-its-denm-msgs ros-jazzy-etsi-its-messages ros-jazzy-etsi-its-msgs ros-jazzy-etsi-its-msgs-utils
  ros-jazzy-etsi-its-primitives-conversion ros-jazzy-udp-msgs
0 upgraded, 18 newly installed, 0 to remove and 227 not upgraded.
Need to get 6261 kB of archives.
After this operation, 105 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

**Comment by riebl** [comment]
Yes, now I can fetch them too. I am glad that it was not a dumb mistake in my configuration but that they were really not there :-)
Thanks again for your efforts!
