### ISSUE TITLE
Wrong publisher in Converter.cpp

### ISSUE THREAD

**Issue by Aruetiise** [ika-rwth-aachen/etsi_its_messages#30]
Hello,
thank you for adding CPM support and support for multiple CDD versions.
I discovered a slight issue with the current code. Both the topic for subscribing and publishing the udp messages in [Converter.cpp](https://github.com/ika-rwth-aachen/etsi_its_messages/blob/cbe394549998b5351807cbc0a14dfcb44211d694/etsi_its_conversion/etsi_its_conversion/src/Converter.cpp) is udp/in not udp/in and udp/out. I think it's easier to get it fixed by someone with access to this repo than creating a pull request. 

Best regards
Julius Becker
FH Aachen

**Comment by lreiher** [comment]
Good catch, thanks for pointing out.
