### ISSUE TITLE
Constants removed from some message definitions

### ISSUE THREAD

**Issue by james-ward** [ika-rwth-aachen/etsi_its_messages#52]
Commit 2d473bbfb10e7c912671a21952479b2bb41a5f39 removed the constants in some of the message definitions.

I noticed it in `etsi_its_msgs/etsi_its_cpm_ts_msgs/msg/CpmContainerId.msg` first, but I think it has happened some other messages during the recreation in that commit.

**Comment by lreiher** [comment]
Please see the breaking changes listed in https://github.com/ika-rwth-aachen/etsi_its_messages/pull/48. The constants in [`CpmContainerId.msg`](https://github.com/ika-rwth-aachen/etsi_its_messages/blob/main/etsi_its_msgs/etsi_its_cpm_ts_msgs/msg/CpmContainerId.msg) have moved to [`WrappedCpmContainer.msg`](https://github.com/ika-rwth-aachen/etsi_its_messages/blob/main/etsi_its_msgs/etsi_its_cpm_ts_msgs/msg/WrappedCpmContainer.msg). With the transition back to the Python-based code generation, we have fixed some bugs and restructured some handling of ASN.1 sytax, in this case the handling of the `CLASS` keyword. Unfortunately, this leads to some breaking changes in the message definitions.

We are going to publish a new release this week, where you will also be able to find all breaking changes in the release notes.

**Comment by james-ward** [comment]
Ah. Sorry, I didn't notice that.

Thanks for the quick reply.

**Comment by lreiher** [comment]
Here's the full list of breaking changes in the release notes :)

https://github.com/ika-rwth-aachen/etsi_its_messages/releases/tag/v3.0.0
